[env:esp32s3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Upload options
upload_port = /dev/ttyUSB0

; Build flags
build_flags =
    -DARDUINO_ARCH_ESP32S3

; Library dependencies
lib_deps =
    ArduinoJson
    knolleary/PubSubClient
    teckel12/NewPing
    ropg/Heltec_ESP32_LoRa_v3
    elvandry13/UltrasonicA02YYUW
