#!/usr/bin/env python3
"""emit_v02_scenarios.py -- freeze the 0091 scenario set into a C++ header.

The consensus test must prove the FIRMWARE's v0.2 engine against the SAME trace
set 0091 measured, not against a re-implemented generator. This script imports
`traces.py` from the 0091 harness (a verbatim copy lives next to it in
`python/detection-sim/`), builds every scenario, and writes the packets and the
ground truth out as a C++ header that the host-side unity test compiles in.

Run:
    python3 python/detection-sim/emit_v02_scenarios.py

It is deterministic: the only randomness is traces.py's per-node seeded RNG, so
re-running it rewrites the same bytes. Re-run it whenever traces.py changes and
commit the regenerated header -- CI does not run this script (the header is the
frozen artifact), which keeps the test hermetic.

Layout of the emitted header (see test/test_consensus_native/test_main.cpp):

    struct Pkt  { float t; uint8_t node; float pm25; };
    struct Scenario { const char* name; ...; const Pkt* pkts; int pkt_count; };
    static const Scenario kScenarios[] = { ... };   // in ALL_SCENARIOS order
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import traces  # noqa: E402  (path set above)

OUT = os.path.abspath(os.path.join(
    HERE, "..", "..", "firmware", "wildfire-node-v1",
    "test", "test_consensus_native", "scenarios_v02.h"))

HEADER = """// GENERATED by python/detection-sim/emit_v02_scenarios.py -- do not hand-edit.
//
// The 0091 scenario set (python/detection-sim/traces.py) frozen as C++ data so
// the host-side consensus test compiles it in with no file I/O. Scenario order
// and seeds match traces.build_all(); every value is the packet the Python
// harness measured. Regenerate with:
//
//     python3 python/detection-sim/emit_v02_scenarios.py
#pragma once

#include <cstdint>

namespace wf {
namespace test {

struct Pkt {
  float t;       // minutes from trace start
  uint8_t node;  // index into the scenario's node-name table
  float pm25;    // ug/m3, as measured by the 0091 harness
};

struct Scenario {
  const char* name;
  const char* const* nodes;
  int node_count;
  const Pkt* pkts;
  int pkt_count;
  float duration_min;
  // ground truth from traces.py
  bool expected_watch;
  float first_rise_at;      // < 0 means "none"
  float expected_watch_at;  // < 0 means "not asserted"
  const char* primary_node;
  float peak_ugm3;
};

"""

FOOTER = """static const Scenario kScenarios[] = {
%s};

static const int kScenarioCount = %d;

}  // namespace test
}  // namespace wf
"""


def fmt_float(v: float) -> str:
    s = "%.3f" % float(v)
    return s


def main() -> int:
    traces_list = traces.build_all()
    parts = [HEADER]
    entries = []

    for idx, tr in enumerate(traces_list):
        node_names = sorted({n for _, n, _ in tr.packets})
        parts.append("static const char* const kNodes_%d[] = {%s};\n" % (
            idx, ", ".join('"%s"' % n for n in node_names)))
        index = {n: i for i, n in enumerate(node_names)}
        rows = []
        for t, node, pm in tr.packets:
            rows.append("{%sf,%d,%sf}" % (fmt_float(t), index[node], fmt_float(pm)))
        pkts = ",\n  ".join(rows)
        parts.append("static const Pkt kPkts_%d[] = {\n  %s\n};\n\n" % (idx, pkts))

        truth = tr.truth
        watch_at = truth.get("expected_watch_at", None)
        entries.append(
            '    {"%s", kNodes_%d, %d, kPkts_%d, %d, %sf, %s, %sf, %sf, "%s", %sf},'
            % (tr.name, idx, len(node_names), idx, len(tr.packets),
               fmt_float(tr.duration_min),
               "true" if truth.get("expected_watch") else "false",
               fmt_float(truth.get("first_rise_at") if truth.get("first_rise_at") is not None else -1.0),
               fmt_float(watch_at if watch_at is not None else -1.0),
               truth.get("primary_node", ""),
               fmt_float(truth.get("peak_ugm3", 0.0))))

    parts.append(FOOTER % ("\n".join(entries), len(traces_list)))
    text = "".join(parts)

    with open(OUT, "w") as fh:
        fh.write(text)

    total = sum(len(tr.packets) for tr in traces_list)
    print("wrote %s" % OUT)
    print("scenarios=%d packets=%d nodes=%d"
          % (len(traces_list), total,
             sum(len({n for _, n, _ in tr.packets}) for tr in traces_list)))
    for tr in traces_list:
        print("  %-28s packets=%4d duration=%6.0f min watch=%s"
              % (tr.name, len(tr.packets), tr.duration_min,
                 tr.truth.get("expected_watch")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
